import cv2
GRAYING_STACKED_WIDGET = 0
FILTER_STACKED_WIDGET = 1
MORPH_STACKED_WIDGET = 2
GRAD_STACKED_WIDGET = 3
THRESH_STACKED_WIDGET = 4
EDGE_STACKED_WIDGET = 5


MEAN_FILTER = 0
GAUSSIAN_FILTER = 1
MEDIAN_FILTER = 2

ERODE_MORPH = cv2.MORPH_ERODE
DILATE_MORPH = cv2.MORPH_DILATE
OPEN_MORPH = cv2.MORPH_OPEN
CLOSE_MORPH = cv2.MORPH_CLOSE
GRADIENT_MORPH = cv2.MORPH_GRADIENT
TOPHAT_MORPH = cv2.MORPH_TOPHAT
BLACKHAT_MORPH = cv2.MORPH_BLACKHAT

RECT_MORPH_SHAPE = cv2.MORPH_RECT
CROSS_MORPH_SHAPE = cv2.MORPH_CROSS
ELLIPSE_MORPH_SHAPE = cv2.MORPH_ELLIPSE

SOBEL_GRAD = 0
SCHARR_GRAD = 1
LAPLACIAN_GRAD = 2

BINARY_THRESH = cv2.THRESH_BINARY
BINARY_INV_THRESH = cv2.THRESH_BINARY_INV
TRUNC_THRESH = cv2.THRESH_TRUNC
TOZERO_THRESH = cv2.THRESH_TOZERO
TOZERO_INV_THRESH = cv2.THRESH_TOZERO_INV
# OTSU_THRESH = cv2.THRESH_OTSU
